services:
  postgres:
    image: postgres:15
    container_name: notif-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notificationdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: notif-app
    depends_on:
      - postgres
      - kafka
    environment:
      DB_CONN: postgres://postgres:postgres@postgres:5432/notificationdb?sslmode=disable
      JWT_SECRET: supersecretkey
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: notifications
      TWILIO_ACCOUNT_SID: your-twilio-account-sid
      TWILIO_AUTH_TOKEN: your-twilio-auth-token
      TWILIO_FROM_NUMBER: your-twilio-from-number
      SENDGRID_API_KEY: your-sendgrid-api-key
      SENDGRID_FROM_EMAIL: your-sendgrid-email
      KAFKA_TOPIC_NOTIFICATIONS_SMS: notifications_sms
      KAFKA_TOPIC_NOTIFICATIONS_EMAIL: notifications_email
      KAFKA_TOPIC_NOTIFICATIONS_DLQ: notifications_dlq
    ports:
      - "8080:8080"
    
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: notif-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: notif-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  prometheus:
    image: prom/prometheus:latest
    container_name: notif-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: notif-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  pgdata:
  